### ISSUE TITLE
Undo pack to VOID

### ISSUE THREAD

**Issue by marsmaantje** [3x1t-5tyl3/3x1t-neos-MT#10]
Make the pack to void of the lokix tip undoable

**Comment by 3x1t-5tyl3** [comment]
So I looked into this. I'm waiting for a bit of info as I can't implement it rn in a way that I personally feel is most useable. I'll need to put this to low priority.

**Comment by 3x1t-5tyl3** [comment]
Decided to not implement this. It's too heavy of a function for something you have to go out of your way to do in the first place.
I don't disagree that it'd be nice. It's just not quite easily doable in a way I feel comfortable with for the tool.
