### ISSUE TITLE
Baking Strokes 

### ISSUE THREAD

**Issue by sirkitree** [3x1t-5tyl3/3x1t-neos-MT#14]
- Baking strokes, and then using the delete strokes function of the tool does not delete the strokes. Perhaps this is intentional, but I expected it would delete them.
- Deleting baked strokes manually (grabbing, then main context menu delete) leaves behind an empty object in the world root.

**Comment by 3x1t-5tyl3** [comment]
Baking strokes is indeed intended to make the strokes seperate and as such makes those not directly deletable.
I'll make sure manual deletion get's rid of the EmptyObject properly though.

**Comment by 3x1t-5tyl3** [comment]
I've looked into it. I have no idea how you managed to get an emptyobject given the system doesn't generate one in root but rather on the stroke top-level and then bakes it. Ergo making it literally impossible to be toplevel (and as such not-directly deletable.)

Reproduction steps with a freshly spawned tool are appreciated.

**Comment by sirkitree** [comment]
Just tried with a freshly spawn tip and it's not happening any longer. I'm unsure how this happened the first time now and question my sanity :P
